name: CI/CD
on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main
  repository_dispatch:
    schedule:
      - cron: '5 12 * * 0'
jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install packages
        run: npm install
      - name: Build
        run: gatsby build
      - name: Create CNAME
        run: |
          touch public/CNAME
          echo "nataliaperezm.com" > public/CNAME
      - name: Deploy
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          npm run deploy
        env:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
